# gcloud builds submit --config=./gcp/pubsub/cloudbuild.yaml . --substitutions=_VERSION=0.11.0
steps:
  - name: maven:3.6.2-jdk-11-slim
    entrypoint: 'mvn'
    args: ['package','-f','./gcp/pubsub/pom.xml']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backup-backfill-pipeline:${_VERSION}', './gcp/pubsub/']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backup-backfill-pipeline:latest', './gcp/pubsub/']
images: ['gcr.io/$PROJECT_ID/backup-backfill-pipeline']
substitutions:
  _VERSION: 0.11.0