# gcloud builds submit --config=./generic/cloudbuild.yaml . --substitutions=_VERSION=0.8.0
steps:
- name: maven:3.6.2-jdk-8-slim
  entrypoint: 'mvn'
  args: ['package','-f','./generic/pom.xml']
- name: gcr.io/cloud-builders/docker
  args: ['build','-t', 'gcr.io/$PROJECT_ID/anonymize:${_VERSION}', './generic/']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/anonymize:latest', './generic/']
images: ['gcr.io/$PROJECT_ID/generic-pipeline']
substitutions:
    _VERSION: 0.8.0