// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collector_payload_v1.proto

package org.datahem.protobuf.collector.v1;

/*-
 * ========================LICENSE_START=================================
 * DataHem
 * %%
 * Copyright (C) 2018 Robert Sahlin and MatHem Sverige AB
 * %%
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =========================LICENSE_END==================================
 */

public final class CollectorPayloadEntityProto {
  private CollectorPayloadEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CollectorPayloadEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.datahem.proto.CollectorPayloadEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string payload = 1;</code>
     */
    java.lang.String getPayload();
    /**
     * <code>optional string payload = 1;</code>
     */
    com.google.protobuf.ByteString
        getPayloadBytes();

    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */
    int getHeadersCount();
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */
    boolean containsHeaders(
        java.lang.String key);
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getHeaders();
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getHeadersMap();
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */

    java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */

    java.lang.String getHeadersOrThrow(
        java.lang.String key);

    /**
     * <code>optional string epoch_millis = 3;</code>
     */
    java.lang.String getEpochMillis();
    /**
     * <code>optional string epoch_millis = 3;</code>
     */
    com.google.protobuf.ByteString
        getEpochMillisBytes();

    /**
     * <code>optional string uuid = 4;</code>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 4;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();
  }
  /**
   * Protobuf type {@code org.datahem.proto.CollectorPayloadEntity}
   */
  public  static final class CollectorPayloadEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.datahem.proto.CollectorPayloadEntity)
      CollectorPayloadEntityOrBuilder {
    // Use CollectorPayloadEntity.newBuilder() to construct.
    private CollectorPayloadEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CollectorPayloadEntity() {
      payload_ = "";
      epochMillis_ = "";
      uuid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CollectorPayloadEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              payload_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                headers_ = com.google.protobuf.MapField.newMapField(
                    HeadersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              headers = input.readMessage(
                  HeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              headers_.getMutableMap().put(headers.getKey(), headers.getValue());
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              epochMillis_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.internal_static_org_datahem_proto_CollectorPayloadEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.internal_static_org_datahem_proto_CollectorPayloadEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity.class, org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity.Builder.class);
    }

    private int bitField0_;
    public static final int PAYLOAD_FIELD_NUMBER = 1;
    private volatile java.lang.Object payload_;
    /**
     * <code>optional string payload = 1;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payload_ = s;
        return s;
      }
    }
    /**
     * <code>optional string payload = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADERS_FIELD_NUMBER = 2;
    private static final class HeadersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.internal_static_org_datahem_proto_CollectorPayloadEntity_HeadersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> headers_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHeaders() {
      if (headers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeadersDefaultEntryHolder.defaultEntry);
      }
      return headers_;
    }

    public int getHeadersCount() {
      return internalGetHeaders().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */

    public boolean containsHeaders(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return internalGetHeaders().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */

    public java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; headers = 2;</code>
     */

    public java.lang.String getHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int EPOCH_MILLIS_FIELD_NUMBER = 3;
    private volatile java.lang.Object epochMillis_;
    /**
     * <code>optional string epoch_millis = 3;</code>
     */
    public java.lang.String getEpochMillis() {
      java.lang.Object ref = epochMillis_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        epochMillis_ = s;
        return s;
      }
    }
    /**
     * <code>optional string epoch_millis = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEpochMillisBytes() {
      java.lang.Object ref = epochMillis_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        epochMillis_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UUID_FIELD_NUMBER = 4;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 4;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string uuid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPayloadBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, payload_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetHeaders().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        headers = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(2, headers);
      }
      if (!getEpochMillisBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, epochMillis_);
      }
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uuid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPayloadBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, payload_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetHeaders().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        headers = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, headers);
      }
      if (!getEpochMillisBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, epochMillis_);
      }
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uuid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity)) {
        return super.equals(obj);
      }
      org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity other = (org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity) obj;

      boolean result = true;
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && internalGetHeaders().equals(
          other.internalGetHeaders());
      result = result && getEpochMillis()
          .equals(other.getEpochMillis());
      result = result && getUuid()
          .equals(other.getUuid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      if (!internalGetHeaders().getMap().isEmpty()) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeaders().hashCode();
      }
      hash = (37 * hash) + EPOCH_MILLIS_FIELD_NUMBER;
      hash = (53 * hash) + getEpochMillis().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.datahem.proto.CollectorPayloadEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.datahem.proto.CollectorPayloadEntity)
        org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.internal_static_org_datahem_proto_CollectorPayloadEntity_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetHeaders();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableHeaders();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.internal_static_org_datahem_proto_CollectorPayloadEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity.class, org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity.Builder.class);
      }

      // Construct using org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        payload_ = "";

        internalGetMutableHeaders().clear();
        epochMillis_ = "";

        uuid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.internal_static_org_datahem_proto_CollectorPayloadEntity_descriptor;
      }

      public org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity getDefaultInstanceForType() {
        return org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity.getDefaultInstance();
      }

      public org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity build() {
        org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity buildPartial() {
        org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity result = new org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.payload_ = payload_;
        result.headers_ = internalGetHeaders();
        result.headers_.makeImmutable();
        result.epochMillis_ = epochMillis_;
        result.uuid_ = uuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity) {
          return mergeFrom((org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity other) {
        if (other == org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity.getDefaultInstance()) return this;
        if (!other.getPayload().isEmpty()) {
          payload_ = other.payload_;
          onChanged();
        }
        internalGetMutableHeaders().mergeFrom(
            other.internalGetHeaders());
        if (!other.getEpochMillis().isEmpty()) {
          epochMillis_ = other.epochMillis_;
          onChanged();
        }
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object payload_ = "";
      /**
       * <code>optional string payload = 1;</code>
       */
      public java.lang.String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          payload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payload = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        java.lang.Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payload = 1;</code>
       */
      public Builder setPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 1;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 1;</code>
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        payload_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> headers_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetHeaders() {
        if (headers_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeadersDefaultEntryHolder.defaultEntry);
        }
        return headers_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableHeaders() {
        onChanged();;
        if (headers_ == null) {
          headers_ = com.google.protobuf.MapField.newMapField(
              HeadersDefaultEntryHolder.defaultEntry);
        }
        if (!headers_.isMutable()) {
          headers_ = headers_.copy();
        }
        return headers_;
      }

      public int getHeadersCount() {
        return internalGetHeaders().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 2;</code>
       */

      public boolean containsHeaders(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetHeaders().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeadersMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
        return getHeadersMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
        return internalGetHeaders().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 2;</code>
       */

      public java.lang.String getHeadersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeaders().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 2;</code>
       */

      public java.lang.String getHeadersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeaders().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearHeaders() {
        getMutableHeaders().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 2;</code>
       */

      public Builder removeHeaders(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        getMutableHeaders().remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableHeaders() {
        return internalGetMutableHeaders().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 2;</code>
       */
      public Builder putHeaders(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        getMutableHeaders().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 2;</code>
       */

      public Builder putAllHeaders(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableHeaders().putAll(values);
        return this;
      }

      private java.lang.Object epochMillis_ = "";
      /**
       * <code>optional string epoch_millis = 3;</code>
       */
      public java.lang.String getEpochMillis() {
        java.lang.Object ref = epochMillis_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          epochMillis_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string epoch_millis = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEpochMillisBytes() {
        java.lang.Object ref = epochMillis_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          epochMillis_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string epoch_millis = 3;</code>
       */
      public Builder setEpochMillis(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        epochMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string epoch_millis = 3;</code>
       */
      public Builder clearEpochMillis() {
        
        epochMillis_ = getDefaultInstance().getEpochMillis();
        onChanged();
        return this;
      }
      /**
       * <code>optional string epoch_millis = 3;</code>
       */
      public Builder setEpochMillisBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        epochMillis_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 4;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 4;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 4;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 4;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.datahem.proto.CollectorPayloadEntity)
    }

    // @@protoc_insertion_point(class_scope:org.datahem.proto.CollectorPayloadEntity)
    private static final org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity();
    }

    public static org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CollectorPayloadEntity>
        PARSER = new com.google.protobuf.AbstractParser<CollectorPayloadEntity>() {
      public CollectorPayloadEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CollectorPayloadEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CollectorPayloadEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CollectorPayloadEntity> getParserForType() {
      return PARSER;
    }

    public org.datahem.protobuf.collector.v1.CollectorPayloadEntityProto.CollectorPayloadEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_datahem_proto_CollectorPayloadEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_datahem_proto_CollectorPayloadEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_datahem_proto_CollectorPayloadEntity_HeadersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_datahem_proto_CollectorPayloadEntity_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032collector_payload_v1.proto\022\021org.datahe" +
      "m.proto\"\306\001\n\026CollectorPayloadEntity\022\017\n\007pa" +
      "yload\030\001 \001(\t\022G\n\007headers\030\002 \003(\01326.org.datah" +
      "em.proto.CollectorPayloadEntity.HeadersE" +
      "ntry\022\024\n\014epoch_millis\030\003 \001(\t\022\014\n\004uuid\030\004 \001(\t" +
      "\032.\n\014HeadersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001B@\n!org.datahem.protobuf.collect" +
      "or.v1B\033CollectorPayloadEntityProtob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_datahem_proto_CollectorPayloadEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_datahem_proto_CollectorPayloadEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_datahem_proto_CollectorPayloadEntity_descriptor,
        new java.lang.String[] { "Payload", "Headers", "EpochMillis", "Uuid", });
    internal_static_org_datahem_proto_CollectorPayloadEntity_HeadersEntry_descriptor =
      internal_static_org_datahem_proto_CollectorPayloadEntity_descriptor.getNestedTypes().get(0);
    internal_static_org_datahem_proto_CollectorPayloadEntity_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_datahem_proto_CollectorPayloadEntity_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
