# gcloud builds submit --config=./generic/cloudbuild.yaml . --substitutions=_VERSION=0.10.0
steps:
  - name: maven:3.6.2-jdk-11-slim
    entrypoint: 'mvn'
    args: ['package','-Dmaven.test.skip=false','-f','./generic/pom.xml']
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t', 'gcr.io/$PROJECT_ID/generic-pipeline:${_VERSION}', './generic/']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/generic-pipeline:latest', './generic/']
images: ['gcr.io/$PROJECT_ID/generic-pipeline']
substitutions:
  _VERSION: 0.9.0
