// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datahem/protobuf/measurementprotocol/v2/measurement_protocol.proto

package org.datahem.protobuf.measurementprotocol.v2;

/*-
 * ========================LICENSE_START=================================
 * Datahem.processor.measurementprotocol
 * %%
 * Copyright (C) 2018 - 2019 Robert Sahlin
 * %%
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */

public final class MeasurementProtocolOuterClass {
  private MeasurementProtocolOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_MeasurementProtocol_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_MeasurementProtocol_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Property_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_CustomDimension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_CustomDimension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_CustomMetric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_CustomMetric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Page_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Page_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_TrafficSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_TrafficSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Geo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Geo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Ecommerce_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Ecommerce_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Experiment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Experiment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Latency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Latency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Refund_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Refund_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Social_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Social_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Promotion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Promotion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Exception_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Exception_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2_Time_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2_Time_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datahem_protobuf_measurementprotocol_v2__ATTRIBUTES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datahem_protobuf_measurementprotocol_v2__ATTRIBUTES_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBdatahem/protobuf/measurementprotocol/v" +
      "2/measurement_protocol.proto\022\'datahem.pr" +
      "otobuf.measurementprotocol.v2\"\251\013\n\023Measur" +
      "ementProtocol\022\017\n\007hitType\030\001 \001(\t\022\020\n\010client" +
      "Id\030\002 \001(\t\022\016\n\006userId\030\003 \001(\t\022\014\n\004date\030\005 \001(\t\022\026" +
      "\n\016nonInteraction\030\006 \001(\005\022\017\n\007version\030\007 \001(\t\022" +
      "R\n\020customDimensions\030\010 \003(\01328.datahem.prot" +
      "obuf.measurementprotocol.v2.CustomDimens" +
      "ion\022L\n\rcustomMetrics\030\t \003(\01325.datahem.pro" +
      "tobuf.measurementprotocol.v2.CustomMetri",
      "c\022?\n\006device\030\n \001(\0132/.datahem.protobuf.mea" +
      "surementprotocol.v2.Device\022E\n\tecommerce\030" +
      "\013 \001(\01322.datahem.protobuf.measurementprot" +
      "ocol.v2.Ecommerce\022=\n\005event\030\014 \001(\0132..datah" +
      "em.protobuf.measurementprotocol.v2.Event" +
      "\022E\n\texception\030\r \001(\01322.datahem.protobuf.m" +
      "easurementprotocol.v2.Exception\022H\n\013exper" +
      "iments\030\016 \003(\01323.datahem.protobuf.measurem" +
      "entprotocol.v2.Experiment\0229\n\003geo\030\017 \001(\0132," +
      ".datahem.protobuf.measurementprotocol.v2",
      ".Geo\022A\n\007latency\030\020 \001(\01320.datahem.protobuf" +
      ".measurementprotocol.v2.Latency\022;\n\004page\030" +
      "\021 \001(\0132-.datahem.protobuf.measurementprot" +
      "ocol.v2.Page\022B\n\010products\030\022 \003(\01320.datahem" +
      ".protobuf.measurementprotocol.v2.Product" +
      "\022F\n\npromotions\030\023 \003(\01322.datahem.protobuf." +
      "measurementprotocol.v2.Promotion\022C\n\010prop" +
      "erty\030\024 \001(\01321.datahem.protobuf.measuremen" +
      "tprotocol.v2.Property\022?\n\006refund\030\025 \001(\0132/." +
      "datahem.protobuf.measurementprotocol.v2.",
      "Refund\022?\n\006social\030\026 \001(\0132/.datahem.protobu" +
      "f.measurementprotocol.v2.Social\022;\n\004time\030" +
      "\027 \001(\0132-.datahem.protobuf.measurementprot" +
      "ocol.v2.Time\022M\n\rtrafficSource\030\030 \001(\01326.da" +
      "tahem.protobuf.measurementprotocol.v2.Tr" +
      "afficSource\022I\n\013transaction\030\031 \001(\01324.datah" +
      "em.protobuf.measurementprotocol.v2.Trans" +
      "action\022I\n\013_ATTRIBUTES\030\032 \001(\01324.datahem.pr" +
      "otobuf.measurementprotocol.v2._ATTRIBUTE" +
      "S\"J\n\010Property\022\022\n\ndataSource\030\001 \001(\t\022\026\n\016gtm",
      "ContainerId\030\002 \001(\t\022\022\n\ntrackingId\030\003 \001(\t\"/\n" +
      "\017CustomDimension\022\r\n\005index\030\001 \001(\005\022\r\n\005value" +
      "\030\002 \001(\t\",\n\014CustomMetric\022\r\n\005index\030\001 \001(\005\022\r\n" +
      "\005value\030\002 \001(\005\"\266\001\n\004Page\022\r\n\005title\030\001 \001(\t\022\013\n\003" +
      "url\030\002 \001(\t\022\020\n\010hostname\030\003 \001(\t\022\014\n\004path\030\004 \001(" +
      "\t\022\017\n\007referer\030\005 \001(\t\022\023\n\013refererHost\030\006 \001(\t\022" +
      "\023\n\013refererPath\030\007 \001(\t\022\025\n\rsearchKeyword\030\010 " +
      "\001(\t\022\020\n\010encoding\030\n \001(\t\022\016\n\006linkId\030\013 \001(\t\"\211\001" +
      "\n\rTrafficSource\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\t\022\017\n\007content\030\003 \001(\t\022\016\n\006medium\030\004 \001(\t\022\016\n\006so",
      "urce\030\005 \001(\t\022\017\n\007keyword\030\006 \001(\t\022\r\n\005gclId\030\007 \001" +
      "(\t\022\r\n\005dclId\030\010 \001(\t\"\235\001\n\006Device\022\023\n\013browserS" +
      "ize\030\001 \001(\t\022\024\n\014flashVersion\030\002 \001(\t\022\023\n\013javaE" +
      "nabled\030\003 \001(\005\022\020\n\010language\030\004 \001(\t\022\024\n\014screen" +
      "Colors\030\005 \001(\t\022\030\n\020screenResolution\030\006 \001(\t\022\021" +
      "\n\tuserAgent\030\007 \001(\t\"I\n\003Geo\022\017\n\007country\030\001 \001(" +
      "\t\022\016\n\006region\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\022\023\n\013cityL" +
      "atLong\030\004 \001(\t\")\n\tEcommerce\022\014\n\004step\030\001 \001(\005\022" +
      "\016\n\006option\030\002 \001(\t\")\n\nExperiment\022\n\n\002id\030\001 \001(" +
      "\t\022\017\n\007variant\030\002 \001(\t\"\312\002\n\007Latency\022\030\n\020domain",
      "LookupTime\030\001 \001(\005\022\034\n\024domContentLoadedTime" +
      "\030\002 \001(\005\022\032\n\022domInteractiveTime\030\003 \001(\005\022\030\n\020pa" +
      "geDownloadTime\030\004 \001(\005\022\024\n\014pageLoadTime\030\005 \001" +
      "(\005\022\027\n\017redirectionTime\030\006 \001(\005\022\034\n\024serverCon" +
      "nectionTime\030\007 \001(\005\022\032\n\022serverResponseTime\030" +
      "\010 \001(\005\022\032\n\022userTimingCategory\030\t \001(\t\022\027\n\017use" +
      "rTimingLabel\030\n \001(\t\022\027\n\017userTimingValue\030\013 " +
      "\001(\005\022\032\n\022userTimingVariable\030\014 \001(\t\"*\n\006Refun" +
      "d\022\016\n\006amount\030\001 \001(\001\022\020\n\010currency\030\002 \001(\t\"\204\003\n\007" +
      "Product\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005bra",
      "nd\030\003 \001(\t\022\017\n\007variant\030\004 \001(\t\022\020\n\010category\030\005 " +
      "\001(\t\022\016\n\006action\030\006 \001(\t\022\022\n\ncouponCode\030\007 \001(\t\022" +
      "\020\n\010currency\030\010 \001(\t\022\020\n\010quantity\030\t \001(\005\022\r\n\005p" +
      "rice\030\n \001(\001\022\024\n\014refundAmount\030\013 \001(\001\022\014\n\004list" +
      "\030\014 \001(\t\022\020\n\010position\030\r \001(\005\022R\n\020customDimens" +
      "ions\030\016 \003(\01328.datahem.protobuf.measuremen" +
      "tprotocol.v2.CustomDimension\022L\n\rcustomMe" +
      "trics\030\017 \003(\01325.datahem.protobuf.measureme" +
      "ntprotocol.v2.CustomMetric\"9\n\006Social\022\016\n\006" +
      "action\030\001 \001(\t\022\016\n\006target\030\002 \001(\t\022\017\n\007network\030",
      "\003 \001(\t\"Y\n\tPromotion\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002" +
      " \001(\t\022\016\n\006action\030\003 \001(\t\022\020\n\010creative\030\004 \001(\t\022\020" +
      "\n\010position\030\005 \001(\t\"\200\001\n\013Transaction\022\n\n\002id\030\001" +
      " \001(\t\022\017\n\007revenue\030\002 \001(\001\022\013\n\003tax\030\003 \001(\001\022\020\n\010sh" +
      "ipping\030\004 \001(\001\022\023\n\013affiliation\030\005 \001(\t\022\020\n\010cur" +
      "rency\030\006 \001(\t\022\016\n\006coupon\030\007 \001(\t\"G\n\005Event\022\020\n\010" +
      "category\030\001 \001(\t\022\016\n\006action\030\002 \001(\t\022\r\n\005label\030" +
      "\003 \001(\t\022\r\n\005value\030\004 \001(\005\"1\n\tException\022\023\n\013des" +
      "cription\030\001 \001(\t\022\017\n\007isFatal\030\002 \001(\005\"\275\001\n\004Time" +
      "\022\020\n\010dateTime\030\001 \001(\t\022\014\n\004date\030\002 \001(\t\022\014\n\004time",
      "\030\003 \001(\t\022\014\n\004year\030\004 \001(\005\022\r\n\005month\030\005 \001(\005\022\014\n\004w" +
      "eek\030\006 \001(\005\022\013\n\003day\030\007 \001(\005\022\014\n\004hour\030\010 \001(\005\022\016\n\006" +
      "minute\030\t \001(\005\022\016\n\006second\030\n \001(\005\022\017\n\007weekDay\030" +
      "\013 \001(\005\022\020\n\010timeZone\030\014 \001(\t\"=\n\013_ATTRIBUTES\022\014" +
      "\n\004uuid\030\001 \001(\t\022\r\n\005topic\030\002 \001(\t\022\021\n\ttimestamp" +
      "\030\003 \001(\tB/\n+org.datahem.protobuf.measureme" +
      "ntprotocol.v2P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_datahem_protobuf_measurementprotocol_v2_MeasurementProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datahem_protobuf_measurementprotocol_v2_MeasurementProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_MeasurementProtocol_descriptor,
        new java.lang.String[] { "HitType", "ClientId", "UserId", "Date", "NonInteraction", "Version", "CustomDimensions", "CustomMetrics", "Device", "Ecommerce", "Event", "Exception", "Experiments", "Geo", "Latency", "Page", "Products", "Promotions", "Property", "Refund", "Social", "Time", "TrafficSource", "Transaction", "ATTRIBUTES", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Property_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datahem_protobuf_measurementprotocol_v2_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Property_descriptor,
        new java.lang.String[] { "DataSource", "GtmContainerId", "TrackingId", });
    internal_static_datahem_protobuf_measurementprotocol_v2_CustomDimension_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datahem_protobuf_measurementprotocol_v2_CustomDimension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_CustomDimension_descriptor,
        new java.lang.String[] { "Index", "Value", });
    internal_static_datahem_protobuf_measurementprotocol_v2_CustomMetric_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_datahem_protobuf_measurementprotocol_v2_CustomMetric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_CustomMetric_descriptor,
        new java.lang.String[] { "Index", "Value", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Page_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_datahem_protobuf_measurementprotocol_v2_Page_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Page_descriptor,
        new java.lang.String[] { "Title", "Url", "Hostname", "Path", "Referer", "RefererHost", "RefererPath", "SearchKeyword", "Encoding", "LinkId", });
    internal_static_datahem_protobuf_measurementprotocol_v2_TrafficSource_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_datahem_protobuf_measurementprotocol_v2_TrafficSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_TrafficSource_descriptor,
        new java.lang.String[] { "Id", "Name", "Content", "Medium", "Source", "Keyword", "GclId", "DclId", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Device_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_datahem_protobuf_measurementprotocol_v2_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Device_descriptor,
        new java.lang.String[] { "BrowserSize", "FlashVersion", "JavaEnabled", "Language", "ScreenColors", "ScreenResolution", "UserAgent", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Geo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_datahem_protobuf_measurementprotocol_v2_Geo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Geo_descriptor,
        new java.lang.String[] { "Country", "Region", "City", "CityLatLong", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Ecommerce_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_datahem_protobuf_measurementprotocol_v2_Ecommerce_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Ecommerce_descriptor,
        new java.lang.String[] { "Step", "Option", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Experiment_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_datahem_protobuf_measurementprotocol_v2_Experiment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Experiment_descriptor,
        new java.lang.String[] { "Id", "Variant", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Latency_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_datahem_protobuf_measurementprotocol_v2_Latency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Latency_descriptor,
        new java.lang.String[] { "DomainLookupTime", "DomContentLoadedTime", "DomInteractiveTime", "PageDownloadTime", "PageLoadTime", "RedirectionTime", "ServerConnectionTime", "ServerResponseTime", "UserTimingCategory", "UserTimingLabel", "UserTimingValue", "UserTimingVariable", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Refund_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_datahem_protobuf_measurementprotocol_v2_Refund_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Refund_descriptor,
        new java.lang.String[] { "Amount", "Currency", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Product_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_datahem_protobuf_measurementprotocol_v2_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Brand", "Variant", "Category", "Action", "CouponCode", "Currency", "Quantity", "Price", "RefundAmount", "List", "Position", "CustomDimensions", "CustomMetrics", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Social_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_datahem_protobuf_measurementprotocol_v2_Social_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Social_descriptor,
        new java.lang.String[] { "Action", "Target", "Network", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Promotion_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_datahem_protobuf_measurementprotocol_v2_Promotion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Promotion_descriptor,
        new java.lang.String[] { "Id", "Name", "Action", "Creative", "Position", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_datahem_protobuf_measurementprotocol_v2_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Transaction_descriptor,
        new java.lang.String[] { "Id", "Revenue", "Tax", "Shipping", "Affiliation", "Currency", "Coupon", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Event_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_datahem_protobuf_measurementprotocol_v2_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Event_descriptor,
        new java.lang.String[] { "Category", "Action", "Label", "Value", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Exception_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_datahem_protobuf_measurementprotocol_v2_Exception_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Exception_descriptor,
        new java.lang.String[] { "Description", "IsFatal", });
    internal_static_datahem_protobuf_measurementprotocol_v2_Time_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_datahem_protobuf_measurementprotocol_v2_Time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2_Time_descriptor,
        new java.lang.String[] { "DateTime", "Date", "Time", "Year", "Month", "Week", "Day", "Hour", "Minute", "Second", "WeekDay", "TimeZone", });
    internal_static_datahem_protobuf_measurementprotocol_v2__ATTRIBUTES_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_datahem_protobuf_measurementprotocol_v2__ATTRIBUTES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datahem_protobuf_measurementprotocol_v2__ATTRIBUTES_descriptor,
        new java.lang.String[] { "Uuid", "Topic", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
