// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datahem/protobuf/measurementprotocol/v2/measurement_protocol.proto

package org.datahem.protobuf.measurementprotocol.v2;

/*-
 * ========================LICENSE_START=================================
 * Datahem.processor.measurementprotocol
 * %%
 * Copyright (C) 2018 - 2019 Robert Sahlin
 * %%
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */

public interface PageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:datahem.protobuf.measurementprotocol.v2.Page)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * dt. The page title.
     * </pre>
     *
     * <code>optional string title = 1;</code>
     */
    java.lang.String getTitle();

    /**
     * <pre>
     * dt. The page title.
     * </pre>
     *
     * <code>optional string title = 1;</code>
     */
    com.google.protobuf.ByteString
    getTitleBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string url = 2;</code>
     */
    java.lang.String getUrl();

    /**
     * <pre>
     * </pre>
     *
     * <code>optional string url = 2;</code>
     */
    com.google.protobuf.ByteString
    getUrlBytes();

    /**
     * <pre>
     * dh. The hostname of the URL.
     * </pre>
     *
     * <code>optional string hostname = 3;</code>
     */
    java.lang.String getHostname();

    /**
     * <pre>
     * dh. The hostname of the URL.
     * </pre>
     *
     * <code>optional string hostname = 3;</code>
     */
    com.google.protobuf.ByteString
    getHostnameBytes();

    /**
     * <pre>
     * dp.The URL path of the page.
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    java.lang.String getPath();

    /**
     * <pre>
     * dp.The URL path of the page.
     * </pre>
     *
     * <code>optional string path = 4;</code>
     */
    com.google.protobuf.ByteString
    getPathBytes();

    /**
     * <pre>
     * dr. The referring page, if the session has a goal completion or transaction. If this page is from the same domain, this is blank.
     * </pre>
     *
     * <code>optional string referer = 5;</code>
     */
    java.lang.String getReferer();

    /**
     * <pre>
     * dr. The referring page, if the session has a goal completion or transaction. If this page is from the same domain, this is blank.
     * </pre>
     *
     * <code>optional string referer = 5;</code>
     */
    com.google.protobuf.ByteString
    getRefererBytes();

    /**
     * <pre>
     * drh
     * </pre>
     *
     * <code>optional string refererHost = 6;</code>
     */
    java.lang.String getRefererHost();

    /**
     * <pre>
     * drh
     * </pre>
     *
     * <code>optional string refererHost = 6;</code>
     */
    com.google.protobuf.ByteString
    getRefererHostBytes();

    /**
     * <pre>
     * drp
     * </pre>
     *
     * <code>optional string refererPath = 7;</code>
     */
    java.lang.String getRefererPath();

    /**
     * <pre>
     * drp
     * </pre>
     *
     * <code>optional string refererPath = 7;</code>
     */
    com.google.protobuf.ByteString
    getRefererPathBytes();

    /**
     * <pre>
     * sst. If this was a search results page, this is the keyword entered.
     * </pre>
     *
     * <code>optional string searchKeyword = 8;</code>
     */
    java.lang.String getSearchKeyword();

    /**
     * <pre>
     * sst. If this was a search results page, this is the keyword entered.
     * </pre>
     *
     * <code>optional string searchKeyword = 8;</code>
     */
    com.google.protobuf.ByteString
    getSearchKeywordBytes();

    /**
     * <pre>
     * string searchCategory = 9;	//If this was a search-results page, this is the category selected.
     * </pre>
     *
     * <code>optional string encoding = 10;</code>
     */
    java.lang.String getEncoding();

    /**
     * <pre>
     * string searchCategory = 9;	//If this was a search-results page, this is the category selected.
     * </pre>
     *
     * <code>optional string encoding = 10;</code>
     */
    com.google.protobuf.ByteString
    getEncodingBytes();

    /**
     * <pre>
     * linkid
     * </pre>
     *
     * <code>optional string linkId = 11;</code>
     */
    java.lang.String getLinkId();

    /**
     * <pre>
     * linkid
     * </pre>
     *
     * <code>optional string linkId = 11;</code>
     */
    com.google.protobuf.ByteString
    getLinkIdBytes();
}
