// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datahem/protobuf/measurementprotocol/v2/measurement_protocol.proto

package org.datahem.protobuf.measurementprotocol.v2;

/*-
 * ========================LICENSE_START=================================
 * Datahem.processor.measurementprotocol
 * %%
 * Copyright (C) 2018 - 2019 Robert Sahlin
 * %%
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */

/**
 * Protobuf type {@code datahem.protobuf.measurementprotocol.v2.Product}
 */
public  final class Product extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datahem.protobuf.measurementprotocol.v2.Product)
    ProductOrBuilder {
  // Use Product.newBuilder() to construct.
  private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Product() {
    id_ = "";
    name_ = "";
    brand_ = "";
    variant_ = "";
    category_ = "";
    action_ = "";
    couponCode_ = "";
    currency_ = "";
    quantity_ = 0L;
    price_ = 0D;
    refundAmount_ = 0D;
    list_ = "";
    position_ = 0L;
    customDimensions_ = java.util.Collections.emptyList();
    customMetrics_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Product(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            brand_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            variant_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            category_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            couponCode_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            currency_ = s;
            break;
          }
          case 72: {

            quantity_ = input.readInt64();
            break;
          }
          case 81: {

            price_ = input.readDouble();
            break;
          }
          case 89: {

            refundAmount_ = input.readDouble();
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            list_ = s;
            break;
          }
          case 104: {

            position_ = input.readInt64();
            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
              customDimensions_ = new java.util.ArrayList<org.datahem.protobuf.measurementprotocol.v2.CustomDimension>();
              mutable_bitField0_ |= 0x00002000;
            }
            customDimensions_.add(
                input.readMessage(org.datahem.protobuf.measurementprotocol.v2.CustomDimension.parser(), extensionRegistry));
            break;
          }
          case 122: {
            if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
              customMetrics_ = new java.util.ArrayList<org.datahem.protobuf.measurementprotocol.v2.CustomMetric>();
              mutable_bitField0_ |= 0x00004000;
            }
            customMetrics_.add(
                input.readMessage(org.datahem.protobuf.measurementprotocol.v2.CustomMetric.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
        customDimensions_ = java.util.Collections.unmodifiableList(customDimensions_);
      }
      if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
        customMetrics_ = java.util.Collections.unmodifiableList(customMetrics_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Product_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Product_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.datahem.protobuf.measurementprotocol.v2.Product.class, org.datahem.protobuf.measurementprotocol.v2.Product.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   *(pr[0-9]{1,3}id)	Product SKU.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *(pr[0-9]{1,3}id)	Product SKU.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *(pr[0-9]{1,3}nm)	Product Name.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *(pr[0-9]{1,3}nm)	Product Name.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BRAND_FIELD_NUMBER = 3;
  private volatile java.lang.Object brand_;
  /**
   * <pre>
   *(pr[0-9]{1,3}br)	The brand associated with the product.
   * </pre>
   *
   * <code>optional string brand = 3;</code>
   */
  public java.lang.String getBrand() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brand_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *(pr[0-9]{1,3}br)	The brand associated with the product.
   * </pre>
   *
   * <code>optional string brand = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBrandBytes() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARIANT_FIELD_NUMBER = 4;
  private volatile java.lang.Object variant_;
  /**
   * <pre>
   *(pr[0-9]{1,3}va)	Product Variant.
   * </pre>
   *
   * <code>optional string variant = 4;</code>
   */
  public java.lang.String getVariant() {
    java.lang.Object ref = variant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      variant_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *(pr[0-9]{1,3}va)	Product Variant.
   * </pre>
   *
   * <code>optional string variant = 4;</code>
   */
  public com.google.protobuf.ByteString
      getVariantBytes() {
    java.lang.Object ref = variant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      variant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 5;
  private volatile java.lang.Object category_;
  /**
   * <pre>
   *(pr[0-9]{1,3}ca)	Product Category.
   * </pre>
   *
   * <code>optional string category = 5;</code>
   */
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *(pr[0-9]{1,3}ca)	Product Category.
   * </pre>
   *
   * <code>optional string category = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 6;
  private volatile java.lang.Object action_;
  /**
   * <pre>
   *pa
   * </pre>
   *
   * <code>optional string action = 6;</code>
   */
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *pa
   * </pre>
   *
   * <code>optional string action = 6;</code>
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUPONCODE_FIELD_NUMBER = 7;
  private volatile java.lang.Object couponCode_;
  /**
   * <pre>
   *(pr[0-9]{1,3}cc) 
   * </pre>
   *
   * <code>optional string couponCode = 7;</code>
   */
  public java.lang.String getCouponCode() {
    java.lang.Object ref = couponCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      couponCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *(pr[0-9]{1,3}cc) 
   * </pre>
   *
   * <code>optional string couponCode = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCouponCodeBytes() {
    java.lang.Object ref = couponCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      couponCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENCY_FIELD_NUMBER = 8;
  private volatile java.lang.Object currency_;
  /**
   * <pre>
   *cu
   * </pre>
   *
   * <code>optional string currency = 8;</code>
   */
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *cu
   * </pre>
   *
   * <code>optional string currency = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 9;
  private long quantity_;
  /**
   * <pre>
   *(pr[0-9]{1,3}qt)	The quantity of the product purchased.
   * </pre>
   *
   * <code>optional int64 quantity = 9;</code>
   */
  public long getQuantity() {
    return quantity_;
  }

  public static final int PRICE_FIELD_NUMBER = 10;
  private double price_;
  /**
   * <pre>
   *(pr[0-9]{1,3}pr)	The price of the product
   * </pre>
   *
   * <code>optional double price = 10;</code>
   */
  public double getPrice() {
    return price_;
  }

  public static final int REFUNDAMOUNT_FIELD_NUMBER = 11;
  private double refundAmount_;
  /**
   * <pre>
   *  The amount processed as part of a refund for a product, expressed as the value passed to Analytics multiplied by 10^6 (e.g., 2.40 would be given as 2400000).
   * </pre>
   *
   * <code>optional double refundAmount = 11;</code>
   */
  public double getRefundAmount() {
    return refundAmount_;
  }

  public static final int LIST_FIELD_NUMBER = 12;
  private volatile java.lang.Object list_;
  /**
   * <pre>
   *pal  Name of the list in which the product is shown, or in which a click occurred. For example, "Home Page Promotion", "Also Viewed", "Recommended For You", "Search Results List", etc.
   * </pre>
   *
   * <code>optional string list = 12;</code>
   */
  public java.lang.String getList() {
    java.lang.Object ref = list_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      list_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *pal  Name of the list in which the product is shown, or in which a click occurred. For example, "Home Page Promotion", "Also Viewed", "Recommended For You", "Search Results List", etc.
   * </pre>
   *
   * <code>optional string list = 12;</code>
   */
  public com.google.protobuf.ByteString
      getListBytes() {
    java.lang.Object ref = list_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      list_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 13;
  private long position_;
  /**
   * <pre>
   *(pr[0-9]{1,3}ps)  Position of the product in the list in which it is shown.
   * </pre>
   *
   * <code>optional int64 position = 13;</code>
   */
  public long getPosition() {
    return position_;
  }

  public static final int CUSTOMDIMENSIONS_FIELD_NUMBER = 14;
  private java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomDimension> customDimensions_;
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
   */
  public java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomDimension> getCustomDimensionsList() {
    return customDimensions_;
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
   */
  public java.util.List<? extends org.datahem.protobuf.measurementprotocol.v2.CustomDimensionOrBuilder> 
      getCustomDimensionsOrBuilderList() {
    return customDimensions_;
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
   */
  public int getCustomDimensionsCount() {
    return customDimensions_.size();
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
   */
  public org.datahem.protobuf.measurementprotocol.v2.CustomDimension getCustomDimensions(int index) {
    return customDimensions_.get(index);
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
   */
  public org.datahem.protobuf.measurementprotocol.v2.CustomDimensionOrBuilder getCustomDimensionsOrBuilder(
      int index) {
    return customDimensions_.get(index);
  }

  public static final int CUSTOMMETRICS_FIELD_NUMBER = 15;
  private java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomMetric> customMetrics_;
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
   */
  public java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomMetric> getCustomMetricsList() {
    return customMetrics_;
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
   */
  public java.util.List<? extends org.datahem.protobuf.measurementprotocol.v2.CustomMetricOrBuilder> 
      getCustomMetricsOrBuilderList() {
    return customMetrics_;
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
   */
  public int getCustomMetricsCount() {
    return customMetrics_.size();
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
   */
  public org.datahem.protobuf.measurementprotocol.v2.CustomMetric getCustomMetrics(int index) {
    return customMetrics_.get(index);
  }
  /**
   * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
   */
  public org.datahem.protobuf.measurementprotocol.v2.CustomMetricOrBuilder getCustomMetricsOrBuilder(
      int index) {
    return customMetrics_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getBrandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, brand_);
    }
    if (!getVariantBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, variant_);
    }
    if (!getCategoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, category_);
    }
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, action_);
    }
    if (!getCouponCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, couponCode_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, currency_);
    }
    if (quantity_ != 0L) {
      output.writeInt64(9, quantity_);
    }
    if (price_ != 0D) {
      output.writeDouble(10, price_);
    }
    if (refundAmount_ != 0D) {
      output.writeDouble(11, refundAmount_);
    }
    if (!getListBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, list_);
    }
    if (position_ != 0L) {
      output.writeInt64(13, position_);
    }
    for (int i = 0; i < customDimensions_.size(); i++) {
      output.writeMessage(14, customDimensions_.get(i));
    }
    for (int i = 0; i < customMetrics_.size(); i++) {
      output.writeMessage(15, customMetrics_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getBrandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, brand_);
    }
    if (!getVariantBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, variant_);
    }
    if (!getCategoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, category_);
    }
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, action_);
    }
    if (!getCouponCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, couponCode_);
    }
    if (!getCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, currency_);
    }
    if (quantity_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, quantity_);
    }
    if (price_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, price_);
    }
    if (refundAmount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, refundAmount_);
    }
    if (!getListBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, list_);
    }
    if (position_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, position_);
    }
    for (int i = 0; i < customDimensions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, customDimensions_.get(i));
    }
    for (int i = 0; i < customMetrics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, customMetrics_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.datahem.protobuf.measurementprotocol.v2.Product)) {
      return super.equals(obj);
    }
    org.datahem.protobuf.measurementprotocol.v2.Product other = (org.datahem.protobuf.measurementprotocol.v2.Product) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && getBrand()
        .equals(other.getBrand());
    result = result && getVariant()
        .equals(other.getVariant());
    result = result && getCategory()
        .equals(other.getCategory());
    result = result && getAction()
        .equals(other.getAction());
    result = result && getCouponCode()
        .equals(other.getCouponCode());
    result = result && getCurrency()
        .equals(other.getCurrency());
    result = result && (getQuantity()
        == other.getQuantity());
    result = result && (
        java.lang.Double.doubleToLongBits(getPrice())
        == java.lang.Double.doubleToLongBits(
            other.getPrice()));
    result = result && (
        java.lang.Double.doubleToLongBits(getRefundAmount())
        == java.lang.Double.doubleToLongBits(
            other.getRefundAmount()));
    result = result && getList()
        .equals(other.getList());
    result = result && (getPosition()
        == other.getPosition());
    result = result && getCustomDimensionsList()
        .equals(other.getCustomDimensionsList());
    result = result && getCustomMetricsList()
        .equals(other.getCustomMetricsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + BRAND_FIELD_NUMBER;
    hash = (53 * hash) + getBrand().hashCode();
    hash = (37 * hash) + VARIANT_FIELD_NUMBER;
    hash = (53 * hash) + getVariant().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + COUPONCODE_FIELD_NUMBER;
    hash = (53 * hash) + getCouponCode().hashCode();
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getQuantity());
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + REFUNDAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRefundAmount()));
    hash = (37 * hash) + LIST_FIELD_NUMBER;
    hash = (53 * hash) + getList().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPosition());
    if (getCustomDimensionsCount() > 0) {
      hash = (37 * hash) + CUSTOMDIMENSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomDimensionsList().hashCode();
    }
    if (getCustomMetricsCount() > 0) {
      hash = (37 * hash) + CUSTOMMETRICS_FIELD_NUMBER;
      hash = (53 * hash) + getCustomMetricsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.datahem.protobuf.measurementprotocol.v2.Product parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.datahem.protobuf.measurementprotocol.v2.Product prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code datahem.protobuf.measurementprotocol.v2.Product}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datahem.protobuf.measurementprotocol.v2.Product)
      org.datahem.protobuf.measurementprotocol.v2.ProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Product_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.datahem.protobuf.measurementprotocol.v2.Product.class, org.datahem.protobuf.measurementprotocol.v2.Product.Builder.class);
    }

    // Construct using org.datahem.protobuf.measurementprotocol.v2.Product.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCustomDimensionsFieldBuilder();
        getCustomMetricsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      name_ = "";

      brand_ = "";

      variant_ = "";

      category_ = "";

      action_ = "";

      couponCode_ = "";

      currency_ = "";

      quantity_ = 0L;

      price_ = 0D;

      refundAmount_ = 0D;

      list_ = "";

      position_ = 0L;

      if (customDimensionsBuilder_ == null) {
        customDimensions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
      } else {
        customDimensionsBuilder_.clear();
      }
      if (customMetricsBuilder_ == null) {
        customMetrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
      } else {
        customMetricsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Product_descriptor;
    }

    public org.datahem.protobuf.measurementprotocol.v2.Product getDefaultInstanceForType() {
      return org.datahem.protobuf.measurementprotocol.v2.Product.getDefaultInstance();
    }

    public org.datahem.protobuf.measurementprotocol.v2.Product build() {
      org.datahem.protobuf.measurementprotocol.v2.Product result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.datahem.protobuf.measurementprotocol.v2.Product buildPartial() {
      org.datahem.protobuf.measurementprotocol.v2.Product result = new org.datahem.protobuf.measurementprotocol.v2.Product(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.brand_ = brand_;
      result.variant_ = variant_;
      result.category_ = category_;
      result.action_ = action_;
      result.couponCode_ = couponCode_;
      result.currency_ = currency_;
      result.quantity_ = quantity_;
      result.price_ = price_;
      result.refundAmount_ = refundAmount_;
      result.list_ = list_;
      result.position_ = position_;
      if (customDimensionsBuilder_ == null) {
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          customDimensions_ = java.util.Collections.unmodifiableList(customDimensions_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.customDimensions_ = customDimensions_;
      } else {
        result.customDimensions_ = customDimensionsBuilder_.build();
      }
      if (customMetricsBuilder_ == null) {
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          customMetrics_ = java.util.Collections.unmodifiableList(customMetrics_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.customMetrics_ = customMetrics_;
      } else {
        result.customMetrics_ = customMetricsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.datahem.protobuf.measurementprotocol.v2.Product) {
        return mergeFrom((org.datahem.protobuf.measurementprotocol.v2.Product)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.datahem.protobuf.measurementprotocol.v2.Product other) {
      if (other == org.datahem.protobuf.measurementprotocol.v2.Product.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getBrand().isEmpty()) {
        brand_ = other.brand_;
        onChanged();
      }
      if (!other.getVariant().isEmpty()) {
        variant_ = other.variant_;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        onChanged();
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (!other.getCouponCode().isEmpty()) {
        couponCode_ = other.couponCode_;
        onChanged();
      }
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        onChanged();
      }
      if (other.getQuantity() != 0L) {
        setQuantity(other.getQuantity());
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getRefundAmount() != 0D) {
        setRefundAmount(other.getRefundAmount());
      }
      if (!other.getList().isEmpty()) {
        list_ = other.list_;
        onChanged();
      }
      if (other.getPosition() != 0L) {
        setPosition(other.getPosition());
      }
      if (customDimensionsBuilder_ == null) {
        if (!other.customDimensions_.isEmpty()) {
          if (customDimensions_.isEmpty()) {
            customDimensions_ = other.customDimensions_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureCustomDimensionsIsMutable();
            customDimensions_.addAll(other.customDimensions_);
          }
          onChanged();
        }
      } else {
        if (!other.customDimensions_.isEmpty()) {
          if (customDimensionsBuilder_.isEmpty()) {
            customDimensionsBuilder_.dispose();
            customDimensionsBuilder_ = null;
            customDimensions_ = other.customDimensions_;
            bitField0_ = (bitField0_ & ~0x00002000);
            customDimensionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCustomDimensionsFieldBuilder() : null;
          } else {
            customDimensionsBuilder_.addAllMessages(other.customDimensions_);
          }
        }
      }
      if (customMetricsBuilder_ == null) {
        if (!other.customMetrics_.isEmpty()) {
          if (customMetrics_.isEmpty()) {
            customMetrics_ = other.customMetrics_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureCustomMetricsIsMutable();
            customMetrics_.addAll(other.customMetrics_);
          }
          onChanged();
        }
      } else {
        if (!other.customMetrics_.isEmpty()) {
          if (customMetricsBuilder_.isEmpty()) {
            customMetricsBuilder_.dispose();
            customMetricsBuilder_ = null;
            customMetrics_ = other.customMetrics_;
            bitField0_ = (bitField0_ & ~0x00004000);
            customMetricsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCustomMetricsFieldBuilder() : null;
          } else {
            customMetricsBuilder_.addAllMessages(other.customMetrics_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.datahem.protobuf.measurementprotocol.v2.Product parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.datahem.protobuf.measurementprotocol.v2.Product) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     *(pr[0-9]{1,3}id)	Product SKU.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}id)	Product SKU.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}id)	Product SKU.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}id)	Product SKU.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}id)	Product SKU.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *(pr[0-9]{1,3}nm)	Product Name.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}nm)	Product Name.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}nm)	Product Name.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}nm)	Product Name.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}nm)	Product Name.
     * </pre>
     *
     * <code>optional string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object brand_ = "";
    /**
     * <pre>
     *(pr[0-9]{1,3}br)	The brand associated with the product.
     * </pre>
     *
     * <code>optional string brand = 3;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}br)	The brand associated with the product.
     * </pre>
     *
     * <code>optional string brand = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}br)	The brand associated with the product.
     * </pre>
     *
     * <code>optional string brand = 3;</code>
     */
    public Builder setBrand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brand_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}br)	The brand associated with the product.
     * </pre>
     *
     * <code>optional string brand = 3;</code>
     */
    public Builder clearBrand() {
      
      brand_ = getDefaultInstance().getBrand();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}br)	The brand associated with the product.
     * </pre>
     *
     * <code>optional string brand = 3;</code>
     */
    public Builder setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brand_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object variant_ = "";
    /**
     * <pre>
     *(pr[0-9]{1,3}va)	Product Variant.
     * </pre>
     *
     * <code>optional string variant = 4;</code>
     */
    public java.lang.String getVariant() {
      java.lang.Object ref = variant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        variant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}va)	Product Variant.
     * </pre>
     *
     * <code>optional string variant = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVariantBytes() {
      java.lang.Object ref = variant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        variant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}va)	Product Variant.
     * </pre>
     *
     * <code>optional string variant = 4;</code>
     */
    public Builder setVariant(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      variant_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}va)	Product Variant.
     * </pre>
     *
     * <code>optional string variant = 4;</code>
     */
    public Builder clearVariant() {
      
      variant_ = getDefaultInstance().getVariant();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}va)	Product Variant.
     * </pre>
     *
     * <code>optional string variant = 4;</code>
     */
    public Builder setVariantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      variant_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <pre>
     *(pr[0-9]{1,3}ca)	Product Category.
     * </pre>
     *
     * <code>optional string category = 5;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}ca)	Product Category.
     * </pre>
     *
     * <code>optional string category = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}ca)	Product Category.
     * </pre>
     *
     * <code>optional string category = 5;</code>
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}ca)	Product Category.
     * </pre>
     *
     * <code>optional string category = 5;</code>
     */
    public Builder clearCategory() {
      
      category_ = getDefaultInstance().getCategory();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}ca)	Product Category.
     * </pre>
     *
     * <code>optional string category = 5;</code>
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      category_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <pre>
     *pa
     * </pre>
     *
     * <code>optional string action = 6;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *pa
     * </pre>
     *
     * <code>optional string action = 6;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *pa
     * </pre>
     *
     * <code>optional string action = 6;</code>
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *pa
     * </pre>
     *
     * <code>optional string action = 6;</code>
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *pa
     * </pre>
     *
     * <code>optional string action = 6;</code>
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object couponCode_ = "";
    /**
     * <pre>
     *(pr[0-9]{1,3}cc) 
     * </pre>
     *
     * <code>optional string couponCode = 7;</code>
     */
    public java.lang.String getCouponCode() {
      java.lang.Object ref = couponCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        couponCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}cc) 
     * </pre>
     *
     * <code>optional string couponCode = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCouponCodeBytes() {
      java.lang.Object ref = couponCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        couponCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}cc) 
     * </pre>
     *
     * <code>optional string couponCode = 7;</code>
     */
    public Builder setCouponCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      couponCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}cc) 
     * </pre>
     *
     * <code>optional string couponCode = 7;</code>
     */
    public Builder clearCouponCode() {
      
      couponCode_ = getDefaultInstance().getCouponCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}cc) 
     * </pre>
     *
     * <code>optional string couponCode = 7;</code>
     */
    public Builder setCouponCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      couponCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <pre>
     *cu
     * </pre>
     *
     * <code>optional string currency = 8;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *cu
     * </pre>
     *
     * <code>optional string currency = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *cu
     * </pre>
     *
     * <code>optional string currency = 8;</code>
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currency_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *cu
     * </pre>
     *
     * <code>optional string currency = 8;</code>
     */
    public Builder clearCurrency() {
      
      currency_ = getDefaultInstance().getCurrency();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *cu
     * </pre>
     *
     * <code>optional string currency = 8;</code>
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currency_ = value;
      onChanged();
      return this;
    }

    private long quantity_ ;
    /**
     * <pre>
     *(pr[0-9]{1,3}qt)	The quantity of the product purchased.
     * </pre>
     *
     * <code>optional int64 quantity = 9;</code>
     */
    public long getQuantity() {
      return quantity_;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}qt)	The quantity of the product purchased.
     * </pre>
     *
     * <code>optional int64 quantity = 9;</code>
     */
    public Builder setQuantity(long value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}qt)	The quantity of the product purchased.
     * </pre>
     *
     * <code>optional int64 quantity = 9;</code>
     */
    public Builder clearQuantity() {
      
      quantity_ = 0L;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <pre>
     *(pr[0-9]{1,3}pr)	The price of the product
     * </pre>
     *
     * <code>optional double price = 10;</code>
     */
    public double getPrice() {
      return price_;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}pr)	The price of the product
     * </pre>
     *
     * <code>optional double price = 10;</code>
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}pr)	The price of the product
     * </pre>
     *
     * <code>optional double price = 10;</code>
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private double refundAmount_ ;
    /**
     * <pre>
     *  The amount processed as part of a refund for a product, expressed as the value passed to Analytics multiplied by 10^6 (e.g., 2.40 would be given as 2400000).
     * </pre>
     *
     * <code>optional double refundAmount = 11;</code>
     */
    public double getRefundAmount() {
      return refundAmount_;
    }
    /**
     * <pre>
     *  The amount processed as part of a refund for a product, expressed as the value passed to Analytics multiplied by 10^6 (e.g., 2.40 would be given as 2400000).
     * </pre>
     *
     * <code>optional double refundAmount = 11;</code>
     */
    public Builder setRefundAmount(double value) {
      
      refundAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *  The amount processed as part of a refund for a product, expressed as the value passed to Analytics multiplied by 10^6 (e.g., 2.40 would be given as 2400000).
     * </pre>
     *
     * <code>optional double refundAmount = 11;</code>
     */
    public Builder clearRefundAmount() {
      
      refundAmount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object list_ = "";
    /**
     * <pre>
     *pal  Name of the list in which the product is shown, or in which a click occurred. For example, "Home Page Promotion", "Also Viewed", "Recommended For You", "Search Results List", etc.
     * </pre>
     *
     * <code>optional string list = 12;</code>
     */
    public java.lang.String getList() {
      java.lang.Object ref = list_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        list_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *pal  Name of the list in which the product is shown, or in which a click occurred. For example, "Home Page Promotion", "Also Viewed", "Recommended For You", "Search Results List", etc.
     * </pre>
     *
     * <code>optional string list = 12;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes() {
      java.lang.Object ref = list_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        list_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *pal  Name of the list in which the product is shown, or in which a click occurred. For example, "Home Page Promotion", "Also Viewed", "Recommended For You", "Search Results List", etc.
     * </pre>
     *
     * <code>optional string list = 12;</code>
     */
    public Builder setList(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      list_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *pal  Name of the list in which the product is shown, or in which a click occurred. For example, "Home Page Promotion", "Also Viewed", "Recommended For You", "Search Results List", etc.
     * </pre>
     *
     * <code>optional string list = 12;</code>
     */
    public Builder clearList() {
      
      list_ = getDefaultInstance().getList();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *pal  Name of the list in which the product is shown, or in which a click occurred. For example, "Home Page Promotion", "Also Viewed", "Recommended For You", "Search Results List", etc.
     * </pre>
     *
     * <code>optional string list = 12;</code>
     */
    public Builder setListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      list_ = value;
      onChanged();
      return this;
    }

    private long position_ ;
    /**
     * <pre>
     *(pr[0-9]{1,3}ps)  Position of the product in the list in which it is shown.
     * </pre>
     *
     * <code>optional int64 position = 13;</code>
     */
    public long getPosition() {
      return position_;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}ps)  Position of the product in the list in which it is shown.
     * </pre>
     *
     * <code>optional int64 position = 13;</code>
     */
    public Builder setPosition(long value) {
      
      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *(pr[0-9]{1,3}ps)  Position of the product in the list in which it is shown.
     * </pre>
     *
     * <code>optional int64 position = 13;</code>
     */
    public Builder clearPosition() {
      
      position_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomDimension> customDimensions_ =
      java.util.Collections.emptyList();
    private void ensureCustomDimensionsIsMutable() {
      if (!((bitField0_ & 0x00002000) == 0x00002000)) {
        customDimensions_ = new java.util.ArrayList<org.datahem.protobuf.measurementprotocol.v2.CustomDimension>(customDimensions_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.datahem.protobuf.measurementprotocol.v2.CustomDimension, org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder, org.datahem.protobuf.measurementprotocol.v2.CustomDimensionOrBuilder> customDimensionsBuilder_;

    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomDimension> getCustomDimensionsList() {
      if (customDimensionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(customDimensions_);
      } else {
        return customDimensionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public int getCustomDimensionsCount() {
      if (customDimensionsBuilder_ == null) {
        return customDimensions_.size();
      } else {
        return customDimensionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomDimension getCustomDimensions(int index) {
      if (customDimensionsBuilder_ == null) {
        return customDimensions_.get(index);
      } else {
        return customDimensionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder setCustomDimensions(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomDimension value) {
      if (customDimensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomDimensionsIsMutable();
        customDimensions_.set(index, value);
        onChanged();
      } else {
        customDimensionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder setCustomDimensions(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder builderForValue) {
      if (customDimensionsBuilder_ == null) {
        ensureCustomDimensionsIsMutable();
        customDimensions_.set(index, builderForValue.build());
        onChanged();
      } else {
        customDimensionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder addCustomDimensions(org.datahem.protobuf.measurementprotocol.v2.CustomDimension value) {
      if (customDimensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomDimensionsIsMutable();
        customDimensions_.add(value);
        onChanged();
      } else {
        customDimensionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder addCustomDimensions(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomDimension value) {
      if (customDimensionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomDimensionsIsMutable();
        customDimensions_.add(index, value);
        onChanged();
      } else {
        customDimensionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder addCustomDimensions(
        org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder builderForValue) {
      if (customDimensionsBuilder_ == null) {
        ensureCustomDimensionsIsMutable();
        customDimensions_.add(builderForValue.build());
        onChanged();
      } else {
        customDimensionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder addCustomDimensions(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder builderForValue) {
      if (customDimensionsBuilder_ == null) {
        ensureCustomDimensionsIsMutable();
        customDimensions_.add(index, builderForValue.build());
        onChanged();
      } else {
        customDimensionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder addAllCustomDimensions(
        java.lang.Iterable<? extends org.datahem.protobuf.measurementprotocol.v2.CustomDimension> values) {
      if (customDimensionsBuilder_ == null) {
        ensureCustomDimensionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, customDimensions_);
        onChanged();
      } else {
        customDimensionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder clearCustomDimensions() {
      if (customDimensionsBuilder_ == null) {
        customDimensions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        customDimensionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public Builder removeCustomDimensions(int index) {
      if (customDimensionsBuilder_ == null) {
        ensureCustomDimensionsIsMutable();
        customDimensions_.remove(index);
        onChanged();
      } else {
        customDimensionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder getCustomDimensionsBuilder(
        int index) {
      return getCustomDimensionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomDimensionOrBuilder getCustomDimensionsOrBuilder(
        int index) {
      if (customDimensionsBuilder_ == null) {
        return customDimensions_.get(index);  } else {
        return customDimensionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public java.util.List<? extends org.datahem.protobuf.measurementprotocol.v2.CustomDimensionOrBuilder> 
         getCustomDimensionsOrBuilderList() {
      if (customDimensionsBuilder_ != null) {
        return customDimensionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(customDimensions_);
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder addCustomDimensionsBuilder() {
      return getCustomDimensionsFieldBuilder().addBuilder(
          org.datahem.protobuf.measurementprotocol.v2.CustomDimension.getDefaultInstance());
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder addCustomDimensionsBuilder(
        int index) {
      return getCustomDimensionsFieldBuilder().addBuilder(
          index, org.datahem.protobuf.measurementprotocol.v2.CustomDimension.getDefaultInstance());
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomDimension customDimensions = 14;</code>
     */
    public java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder> 
         getCustomDimensionsBuilderList() {
      return getCustomDimensionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.datahem.protobuf.measurementprotocol.v2.CustomDimension, org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder, org.datahem.protobuf.measurementprotocol.v2.CustomDimensionOrBuilder> 
        getCustomDimensionsFieldBuilder() {
      if (customDimensionsBuilder_ == null) {
        customDimensionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.datahem.protobuf.measurementprotocol.v2.CustomDimension, org.datahem.protobuf.measurementprotocol.v2.CustomDimension.Builder, org.datahem.protobuf.measurementprotocol.v2.CustomDimensionOrBuilder>(
                customDimensions_,
                ((bitField0_ & 0x00002000) == 0x00002000),
                getParentForChildren(),
                isClean());
        customDimensions_ = null;
      }
      return customDimensionsBuilder_;
    }

    private java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomMetric> customMetrics_ =
      java.util.Collections.emptyList();
    private void ensureCustomMetricsIsMutable() {
      if (!((bitField0_ & 0x00004000) == 0x00004000)) {
        customMetrics_ = new java.util.ArrayList<org.datahem.protobuf.measurementprotocol.v2.CustomMetric>(customMetrics_);
        bitField0_ |= 0x00004000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.datahem.protobuf.measurementprotocol.v2.CustomMetric, org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder, org.datahem.protobuf.measurementprotocol.v2.CustomMetricOrBuilder> customMetricsBuilder_;

    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomMetric> getCustomMetricsList() {
      if (customMetricsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(customMetrics_);
      } else {
        return customMetricsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public int getCustomMetricsCount() {
      if (customMetricsBuilder_ == null) {
        return customMetrics_.size();
      } else {
        return customMetricsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomMetric getCustomMetrics(int index) {
      if (customMetricsBuilder_ == null) {
        return customMetrics_.get(index);
      } else {
        return customMetricsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder setCustomMetrics(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomMetric value) {
      if (customMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomMetricsIsMutable();
        customMetrics_.set(index, value);
        onChanged();
      } else {
        customMetricsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder setCustomMetrics(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder builderForValue) {
      if (customMetricsBuilder_ == null) {
        ensureCustomMetricsIsMutable();
        customMetrics_.set(index, builderForValue.build());
        onChanged();
      } else {
        customMetricsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder addCustomMetrics(org.datahem.protobuf.measurementprotocol.v2.CustomMetric value) {
      if (customMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomMetricsIsMutable();
        customMetrics_.add(value);
        onChanged();
      } else {
        customMetricsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder addCustomMetrics(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomMetric value) {
      if (customMetricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCustomMetricsIsMutable();
        customMetrics_.add(index, value);
        onChanged();
      } else {
        customMetricsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder addCustomMetrics(
        org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder builderForValue) {
      if (customMetricsBuilder_ == null) {
        ensureCustomMetricsIsMutable();
        customMetrics_.add(builderForValue.build());
        onChanged();
      } else {
        customMetricsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder addCustomMetrics(
        int index, org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder builderForValue) {
      if (customMetricsBuilder_ == null) {
        ensureCustomMetricsIsMutable();
        customMetrics_.add(index, builderForValue.build());
        onChanged();
      } else {
        customMetricsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder addAllCustomMetrics(
        java.lang.Iterable<? extends org.datahem.protobuf.measurementprotocol.v2.CustomMetric> values) {
      if (customMetricsBuilder_ == null) {
        ensureCustomMetricsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, customMetrics_);
        onChanged();
      } else {
        customMetricsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder clearCustomMetrics() {
      if (customMetricsBuilder_ == null) {
        customMetrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
      } else {
        customMetricsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public Builder removeCustomMetrics(int index) {
      if (customMetricsBuilder_ == null) {
        ensureCustomMetricsIsMutable();
        customMetrics_.remove(index);
        onChanged();
      } else {
        customMetricsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder getCustomMetricsBuilder(
        int index) {
      return getCustomMetricsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomMetricOrBuilder getCustomMetricsOrBuilder(
        int index) {
      if (customMetricsBuilder_ == null) {
        return customMetrics_.get(index);  } else {
        return customMetricsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public java.util.List<? extends org.datahem.protobuf.measurementprotocol.v2.CustomMetricOrBuilder> 
         getCustomMetricsOrBuilderList() {
      if (customMetricsBuilder_ != null) {
        return customMetricsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(customMetrics_);
      }
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder addCustomMetricsBuilder() {
      return getCustomMetricsFieldBuilder().addBuilder(
          org.datahem.protobuf.measurementprotocol.v2.CustomMetric.getDefaultInstance());
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder addCustomMetricsBuilder(
        int index) {
      return getCustomMetricsFieldBuilder().addBuilder(
          index, org.datahem.protobuf.measurementprotocol.v2.CustomMetric.getDefaultInstance());
    }
    /**
     * <code>repeated .datahem.protobuf.measurementprotocol.v2.CustomMetric customMetrics = 15;</code>
     */
    public java.util.List<org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder> 
         getCustomMetricsBuilderList() {
      return getCustomMetricsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.datahem.protobuf.measurementprotocol.v2.CustomMetric, org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder, org.datahem.protobuf.measurementprotocol.v2.CustomMetricOrBuilder> 
        getCustomMetricsFieldBuilder() {
      if (customMetricsBuilder_ == null) {
        customMetricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.datahem.protobuf.measurementprotocol.v2.CustomMetric, org.datahem.protobuf.measurementprotocol.v2.CustomMetric.Builder, org.datahem.protobuf.measurementprotocol.v2.CustomMetricOrBuilder>(
                customMetrics_,
                ((bitField0_ & 0x00004000) == 0x00004000),
                getParentForChildren(),
                isClean());
        customMetrics_ = null;
      }
      return customMetricsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:datahem.protobuf.measurementprotocol.v2.Product)
  }

  // @@protoc_insertion_point(class_scope:datahem.protobuf.measurementprotocol.v2.Product)
  private static final org.datahem.protobuf.measurementprotocol.v2.Product DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.datahem.protobuf.measurementprotocol.v2.Product();
  }

  public static org.datahem.protobuf.measurementprotocol.v2.Product getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Product>
      PARSER = new com.google.protobuf.AbstractParser<Product>() {
    public Product parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Product> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Product> getParserForType() {
    return PARSER;
  }

  public org.datahem.protobuf.measurementprotocol.v2.Product getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

