// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datahem/protobuf/measurementprotocol/v2/measurement_protocol.proto

package org.datahem.protobuf.measurementprotocol.v2;

/*-
 * ========================LICENSE_START=================================
 * Datahem.processor.measurementprotocol
 * %%
 * Copyright (C) 2018 - 2019 Robert Sahlin
 * %%
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */

/**
 * Protobuf type {@code datahem.protobuf.measurementprotocol.v2.Property}
 */
public final class Property extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:datahem.protobuf.measurementprotocol.v2.Property)
        PropertyOrBuilder {
    // Use Property.newBuilder() to construct.
    private Property(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Property() {
        dataSource_ = "";
        gtmContainerId_ = "";
        trackingId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private Property(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        dataSource_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        gtmContainerId_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        trackingId_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Property_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Property_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.datahem.protobuf.measurementprotocol.v2.Property.class, org.datahem.protobuf.measurementprotocol.v2.Property.Builder.class);
    }

    public static final int DATASOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataSource_;

    /**
     * <pre>
     * ds
     * </pre>
     *
     * <code>optional string dataSource = 1;</code>
     */
    public java.lang.String getDataSource() {
        java.lang.Object ref = dataSource_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dataSource_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * ds
     * </pre>
     *
     * <code>optional string dataSource = 1;</code>
     */
    public com.google.protobuf.ByteString
    getDataSourceBytes() {
        java.lang.Object ref = dataSource_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            dataSource_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int GTMCONTAINERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object gtmContainerId_;

    /**
     * <pre>
     * gtm
     * </pre>
     *
     * <code>optional string gtmContainerId = 2;</code>
     */
    public java.lang.String getGtmContainerId() {
        java.lang.Object ref = gtmContainerId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            gtmContainerId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * gtm
     * </pre>
     *
     * <code>optional string gtmContainerId = 2;</code>
     */
    public com.google.protobuf.ByteString
    getGtmContainerIdBytes() {
        java.lang.Object ref = gtmContainerId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            gtmContainerId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int TRACKINGID_FIELD_NUMBER = 3;
    private volatile java.lang.Object trackingId_;

    /**
     * <pre>
     * tid
     * </pre>
     *
     * <code>optional string trackingId = 3;</code>
     */
    public java.lang.String getTrackingId() {
        java.lang.Object ref = trackingId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            trackingId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * tid
     * </pre>
     *
     * <code>optional string trackingId = 3;</code>
     */
    public com.google.protobuf.ByteString
    getTrackingIdBytes() {
        java.lang.Object ref = trackingId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            trackingId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getDataSourceBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataSource_);
        }
        if (!getGtmContainerIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gtmContainerId_);
        }
        if (!getTrackingIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, trackingId_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getDataSourceBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataSource_);
        }
        if (!getGtmContainerIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gtmContainerId_);
        }
        if (!getTrackingIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, trackingId_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.datahem.protobuf.measurementprotocol.v2.Property)) {
            return super.equals(obj);
        }
        org.datahem.protobuf.measurementprotocol.v2.Property other = (org.datahem.protobuf.measurementprotocol.v2.Property) obj;

        boolean result = true;
        result = result && getDataSource()
                .equals(other.getDataSource());
        result = result && getGtmContainerId()
                .equals(other.getGtmContainerId());
        result = result && getTrackingId()
                .equals(other.getTrackingId());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + DATASOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getDataSource().hashCode();
        hash = (37 * hash) + GTMCONTAINERID_FIELD_NUMBER;
        hash = (53 * hash) + getGtmContainerId().hashCode();
        hash = (37 * hash) + TRACKINGID_FIELD_NUMBER;
        hash = (53 * hash) + getTrackingId().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.datahem.protobuf.measurementprotocol.v2.Property prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code datahem.protobuf.measurementprotocol.v2.Property}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:datahem.protobuf.measurementprotocol.v2.Property)
            org.datahem.protobuf.measurementprotocol.v2.PropertyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Property_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Property_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.datahem.protobuf.measurementprotocol.v2.Property.class, org.datahem.protobuf.measurementprotocol.v2.Property.Builder.class);
        }

        // Construct using org.datahem.protobuf.measurementprotocol.v2.Property.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            dataSource_ = "";

            gtmContainerId_ = "";

            trackingId_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.datahem.protobuf.measurementprotocol.v2.MeasurementProtocolOuterClass.internal_static_datahem_protobuf_measurementprotocol_v2_Property_descriptor;
        }

        public org.datahem.protobuf.measurementprotocol.v2.Property getDefaultInstanceForType() {
            return org.datahem.protobuf.measurementprotocol.v2.Property.getDefaultInstance();
        }

        public org.datahem.protobuf.measurementprotocol.v2.Property build() {
            org.datahem.protobuf.measurementprotocol.v2.Property result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public org.datahem.protobuf.measurementprotocol.v2.Property buildPartial() {
            org.datahem.protobuf.measurementprotocol.v2.Property result = new org.datahem.protobuf.measurementprotocol.v2.Property(this);
            result.dataSource_ = dataSource_;
            result.gtmContainerId_ = gtmContainerId_;
            result.trackingId_ = trackingId_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.datahem.protobuf.measurementprotocol.v2.Property) {
                return mergeFrom((org.datahem.protobuf.measurementprotocol.v2.Property) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.datahem.protobuf.measurementprotocol.v2.Property other) {
            if (other == org.datahem.protobuf.measurementprotocol.v2.Property.getDefaultInstance()) return this;
            if (!other.getDataSource().isEmpty()) {
                dataSource_ = other.dataSource_;
                onChanged();
            }
            if (!other.getGtmContainerId().isEmpty()) {
                gtmContainerId_ = other.gtmContainerId_;
                onChanged();
            }
            if (!other.getTrackingId().isEmpty()) {
                trackingId_ = other.trackingId_;
                onChanged();
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            org.datahem.protobuf.measurementprotocol.v2.Property parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (org.datahem.protobuf.measurementprotocol.v2.Property) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object dataSource_ = "";

        /**
         * <pre>
         * ds
         * </pre>
         *
         * <code>optional string dataSource = 1;</code>
         */
        public java.lang.String getDataSource() {
            java.lang.Object ref = dataSource_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dataSource_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * ds
         * </pre>
         *
         * <code>optional string dataSource = 1;</code>
         */
        public com.google.protobuf.ByteString
        getDataSourceBytes() {
            java.lang.Object ref = dataSource_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dataSource_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * ds
         * </pre>
         *
         * <code>optional string dataSource = 1;</code>
         */
        public Builder setDataSource(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            dataSource_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * ds
         * </pre>
         *
         * <code>optional string dataSource = 1;</code>
         */
        public Builder clearDataSource() {

            dataSource_ = getDefaultInstance().getDataSource();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * ds
         * </pre>
         *
         * <code>optional string dataSource = 1;</code>
         */
        public Builder setDataSourceBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            dataSource_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object gtmContainerId_ = "";

        /**
         * <pre>
         * gtm
         * </pre>
         *
         * <code>optional string gtmContainerId = 2;</code>
         */
        public java.lang.String getGtmContainerId() {
            java.lang.Object ref = gtmContainerId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                gtmContainerId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * gtm
         * </pre>
         *
         * <code>optional string gtmContainerId = 2;</code>
         */
        public com.google.protobuf.ByteString
        getGtmContainerIdBytes() {
            java.lang.Object ref = gtmContainerId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                gtmContainerId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * gtm
         * </pre>
         *
         * <code>optional string gtmContainerId = 2;</code>
         */
        public Builder setGtmContainerId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            gtmContainerId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * gtm
         * </pre>
         *
         * <code>optional string gtmContainerId = 2;</code>
         */
        public Builder clearGtmContainerId() {

            gtmContainerId_ = getDefaultInstance().getGtmContainerId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * gtm
         * </pre>
         *
         * <code>optional string gtmContainerId = 2;</code>
         */
        public Builder setGtmContainerIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            gtmContainerId_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object trackingId_ = "";

        /**
         * <pre>
         * tid
         * </pre>
         *
         * <code>optional string trackingId = 3;</code>
         */
        public java.lang.String getTrackingId() {
            java.lang.Object ref = trackingId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                trackingId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * tid
         * </pre>
         *
         * <code>optional string trackingId = 3;</code>
         */
        public com.google.protobuf.ByteString
        getTrackingIdBytes() {
            java.lang.Object ref = trackingId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                trackingId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * tid
         * </pre>
         *
         * <code>optional string trackingId = 3;</code>
         */
        public Builder setTrackingId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            trackingId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * tid
         * </pre>
         *
         * <code>optional string trackingId = 3;</code>
         */
        public Builder clearTrackingId() {

            trackingId_ = getDefaultInstance().getTrackingId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * tid
         * </pre>
         *
         * <code>optional string trackingId = 3;</code>
         */
        public Builder setTrackingIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            trackingId_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:datahem.protobuf.measurementprotocol.v2.Property)
    }

    // @@protoc_insertion_point(class_scope:datahem.protobuf.measurementprotocol.v2.Property)
    private static final org.datahem.protobuf.measurementprotocol.v2.Property DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.datahem.protobuf.measurementprotocol.v2.Property();
    }

    public static org.datahem.protobuf.measurementprotocol.v2.Property getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Property>
            PARSER = new com.google.protobuf.AbstractParser<Property>() {
        public Property parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Property(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Property> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Property> getParserForType() {
        return PARSER;
    }

    public org.datahem.protobuf.measurementprotocol.v2.Property getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

